version: '3'
services:
  mysql:
    container_name: mysql
    hostname: 'mysql'
    build: .
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
